#!/usr/bin/env python3
"""
Prime Mesh R2Q - H-Exc T_J grid extraction audit.

Extracts the sampled grid rule used by the H-Exc/SR11 bridge path exports.
"""

from __future__ import annotations

import csv
import math
import time
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List

import numpy as np
import pandas as pd


OUT_DIR = Path(__file__).resolve().parent
P0 = 500_000_000


def geometric_h_values(max_h: int, max_points: int = 36) -> List[int]:
    max_h = int(max_h)
    vals = {1, 2, 3, 4, 5, 8, 10, 16, 32, 64, 128}
    if max_h > 1:
        for v in np.geomspace(1, max_h, num=max_points):
            vals.add(int(round(v)))
    vals.add(max_h)
    return sorted(v for v in vals if 1 <= v <= max_h)


def write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    keys: List[str] = []
    seen = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                keys.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def boolish(x) -> bool:
    if isinstance(x, (bool, np.bool_)):
        return bool(x)
    if pd.isna(x):
        return False
    if isinstance(x, (int, float, np.integer, np.floating)):
        return bool(x)
    return str(x).strip().lower() in {"true", "1", "yes", "y"}


def nearest_distances(points: np.ndarray, anchors: np.ndarray) -> np.ndarray:
    if len(points) == 0:
        return np.array([], dtype=np.float64)
    if len(anchors) == 0:
        return np.full(len(points), np.nan, dtype=np.float64)
    idx = np.searchsorted(anchors, points)
    left = np.where(idx > 0, anchors[np.maximum(idx - 1, 0)], anchors[0])
    right = np.where(idx < len(anchors), anchors[np.minimum(idx, len(anchors) - 1)], anchors[-1])
    return np.minimum(np.abs(points - left), np.abs(points - right)).astype(float)


def update_manifest(paths: Iterable[Path]) -> None:
    manifest = OUT_DIR / "deposit_manifest.csv"
    existing = pd.read_csv(manifest) if manifest.exists() else pd.DataFrame()
    rows = [] if existing.empty else existing.to_dict("records")
    by_name = {str(r.get("filename")): i for i, r in enumerate(rows)}
    now = time.strftime("%Y-%m-%dT%H:%M:%S")
    for path in paths:
        rec = {
            "filename": path.name,
            "path": str(path),
            "bytes": path.stat().st_size if path.exists() else 0,
            "status": "new",
            "updated_at": now,
            "note": "H-Exc T_J grid extraction audit output",
        }
        if path.name in by_name:
            rows[by_name[path.name]] = rec
        else:
            rows.append(rec)
    write_csv(manifest, rows)


def offset_string(offsets: List[int]) -> str:
    s = ",".join(str(x) for x in offsets)
    return s if len(s) <= 600 else s[:600] + "...truncated"


def make_note(summary: Dict[str, object], paths: Dict[str, Path]) -> str:
    status = "PASS" if summary["pass_tj_grid_extraction_empirical"] else "REPAIR NEEDED"
    lines = [
        "# Prime Mesh R2Q - H-Exc T_J Grid Extraction Audit v1",
        "",
        f"**Status:** {status}",
        "",
        "## Extracted Rule",
        "",
        "Script inspection gives the proof-facing rule:",
        "",
        "```text",
        "SR11 first builds h-samples with geometric_h_values(max_h):",
        "{1,2,3,4,5,8,10,16,32,64,128} plus round(geomspace(1,max_h,36)) plus max_h.",
        "",
        "Route A then defines, for a selected candidate J=(block_id,y,h):",
        "T_J = {y} union {y+r : r is an available SR11 h-sample for (block_id,y), r <= h} union {y+h}.",
        "```",
        "",
        "The h-grid rule is independent of Lambda events. Candidate selection may be empirical, but the sampled offsets are not generated by inspecting prime-shock events.",
        "",
        "## Summary",
        "",
        "```text",
    ]
    for key in [
        "rows",
        "post_P0_rows",
        "left_endpoint_missing_count",
        "right_endpoint_missing_count",
        "post_P0_left_endpoint_missing_count",
        "post_P0_right_endpoint_missing_count",
        "simple_geometric_h_match_count",
        "simple_geometric_h_mismatch_count",
        "post_P0_simple_geometric_h_match_count",
        "post_P0_simple_geometric_h_mismatch_count",
        "unique_offset_patterns",
        "unique_offset_patterns_post_P0",
        "pattern_coverage_top_1",
        "pattern_coverage_top_5",
        "pattern_coverage_top_10",
        "samples_on_lambda_event_fraction",
        "samples_near_lambda_event_fraction",
        "event_to_sample_alignment_score_mean",
        "script_inspection_lambda_dependent_grid",
        "proof_safe_TJ_rule_available",
        "recommended_TJ_definition",
        "pass_tj_grid_extraction_empirical",
    ]:
        lines.append(f"{key} = {summary.get(key)}")
    lines += [
        "```",
        "",
        "## Interpretation",
        "",
        "The clean replacement theorem should not define `T_J` as the full integer grid. It should define `T_J` as the Route-A SR11 subgrid above. A simpler `{0} union geometric_h_values(h)` rule matches most rows, but not all rows, including one post-P0 row.",
        "",
        "## Files",
        "",
    ]
    for label, path in paths.items():
        lines.append(f"- `{label}`: `{path.name}`")
    lines.append("")
    return "\n".join(lines)


def aggregate(rows_df: pd.DataFrame, key: str) -> List[Dict[str, object]]:
    if key not in rows_df.columns:
        return []
    out = []
    for value, g in rows_df.groupby(key, dropna=False):
        out.append(
            {
                "group_field": key,
                "group_value": value,
                "rows": int(len(g)),
                "post_P0_rows": int(g["post_P0_flag"].sum()),
                "sample_count_min": int(g["sample_count"].min()),
                "sample_count_max": int(g["sample_count"].max()),
                "sample_count_mean": float(g["sample_count"].mean()),
                "simple_geometric_h_match_frac": float(g["simple_geometric_h_match_flag"].mean()),
                "left_endpoint_missing_count": int((~g["left_endpoint_sampled_flag"]).sum()),
                "right_endpoint_missing_count": int((~g["right_endpoint_sampled_flag"]).sum()),
                "alignment_score_mean": float(g["event_to_sample_alignment_score"].mean()) if "event_to_sample_alignment_score" in g else math.nan,
            }
        )
    return out


def main() -> None:
    samples_path = OUT_DIR / "prime_mesh_r2q_hexc_bridge_path_samples_v1.csv"
    samplegrid_path = OUT_DIR / "prime_mesh_r2q_hexc_primeshock_samplegrid_structure_rows.csv"
    primitive_path = OUT_DIR / "prime_mesh_r2q_rawr2q_primitive_decomposition_rows_v3.csv"
    for path in [samples_path, samplegrid_path, primitive_path]:
        if not path.exists():
            raise FileNotFoundError(path)

    samples = pd.read_csv(samples_path)
    grid = pd.read_csv(samplegrid_path)
    primitive = pd.read_csv(primitive_path)

    grid_cols = [
        "candidate_id",
        "lambda_event_count",
        "samples_on_event_count",
        "event_to_sample_alignment_score",
        "nearest_sample_distance_to_event_mean",
        "nearest_sample_distance_to_event_max",
        "K_prime_sampled",
        "optional_K_prime_full",
        "optional_full_to_sampled_energy_ratio",
    ]
    grid_small = grid[[c for c in grid_cols if c in grid.columns]].drop_duplicates("candidate_id")
    prim_cols = [
        "candidate_id",
        "Q_R2Q",
        "E_theta_sign",
        "threshold_relevant_flag",
        "forbidden_flag",
        "finite_zone_flag",
        "row_status",
    ]
    prim_small = primitive[[c for c in prim_cols if c in primitive.columns]].drop_duplicates("candidate_id")

    rows: List[Dict[str, object]] = []
    pattern_counter: Counter[str] = Counter()
    pattern_counter_post: Counter[str] = Counter()
    grouped = samples.groupby("candidate_id", sort=False)
    for candidate_id, g in grouped:
        g = g.sort_values("offset")
        block_id = int(g["block_id"].iloc[0])
        y = int(g["y"].iloc[0])
        h = int(g["h"].iloc[0])
        p_star = int(g["p_star"].iloc[0])
        offsets = sorted(set(int(x) for x in g["offset"].to_numpy()))
        gaps = np.diff(offsets) if len(offsets) > 1 else np.array([], dtype=int)
        predicted = [0] + geometric_h_values(h)
        predicted = sorted(set(predicted))
        symdiff = sorted(set(offsets).symmetric_difference(predicted))
        pattern = offset_string(offsets)
        pattern_counter[pattern] += 1
        if p_star >= P0:
            pattern_counter_post[pattern] += 1

        rows.append(
            {
                "candidate_id": candidate_id,
                "block_id": block_id,
                "y": y,
                "h": h,
                "p_star": p_star,
                "post_P0_flag": bool(p_star >= P0),
                "sample_count": int(len(offsets)),
                "sample_count_over_h": float(len(offsets) / h) if h else math.nan,
                "offsets_sorted": pattern,
                "offsets_full_length": int(len(",".join(str(x) for x in offsets))),
                "sample_offsets_min": int(min(offsets)),
                "sample_offsets_max": int(max(offsets)),
                "left_endpoint_sampled_flag": bool(0 in offsets),
                "right_endpoint_sampled_flag": bool(h in offsets),
                "offset_gap_pattern": offset_string([int(x) for x in gaps[:80]]),
                "sample_offset_gaps_max": int(gaps.max()) if len(gaps) else 0,
                "sample_offset_gaps_mean": float(gaps.mean()) if len(gaps) else math.nan,
                "sample_offset_gaps_median": float(np.median(gaps)) if len(gaps) else math.nan,
                "simple_geometric_h_match_flag": bool(offsets == predicted),
                "simple_geometric_h_symmetric_difference_count": int(len(symdiff)),
                "simple_geometric_h_missing_offsets": offset_string([x for x in predicted if x not in set(offsets)]),
                "simple_geometric_h_extra_offsets": offset_string([x for x in offsets if x not in set(predicted)]),
                "grid_origin_rule": "routeA_sr11_available_subgrid_plus_endpoints",
                "grid_depends_on_Lambda_by_code_flag": False,
                "grid_depends_on_candidate_h_flag": True,
                "grid_depends_on_parent_sr11_y_path_flag": True,
                "grid_endpoint_complete_flag": bool(0 in offsets and h in offsets),
            }
        )

    rows_df = pd.DataFrame(rows)
    rows_df = rows_df.merge(grid_small, on="candidate_id", how="left")
    rows_df = rows_df.merge(prim_small, on="candidate_id", how="left")

    # Event-nearness summary: "near" means sample exactly on or within 1 integer step
    # from a Lambda event, using the samplegrid audit's mean/max event-to-sample distances
    # when exact event rows are not separately exported.
    if "samples_on_event_count" in rows_df and "lambda_event_count" in rows_df:
        total_samples_on_events = float(rows_df["samples_on_event_count"].fillna(0).sum())
        total_samples = float(rows_df["sample_count"].sum())
        samples_on_event_fraction = total_samples_on_events / total_samples if total_samples else math.nan
    else:
        samples_on_event_fraction = math.nan

    near_proxy = rows_df["nearest_sample_distance_to_event_mean"].fillna(np.inf) <= 1.0 if "nearest_sample_distance_to_event_mean" in rows_df else pd.Series(False, index=rows_df.index)
    samples_near_fraction = float(near_proxy.mean())

    post = rows_df[rows_df["post_P0_flag"] == True]
    top_counts = pattern_counter.most_common(10)
    top_rows = []
    total = len(rows_df)
    post_total = len(post)
    for rank, (pattern, count) in enumerate(top_counts, start=1):
        top_rows.append(
            {
                "rank": rank,
                "rows": count,
                "coverage": count / total if total else math.nan,
                "post_P0_rows": pattern_counter_post.get(pattern, 0),
                "post_P0_coverage": pattern_counter_post.get(pattern, 0) / post_total if post_total else math.nan,
                "pattern": pattern,
            }
        )

    summary = {
        "rows": int(len(rows_df)),
        "post_P0_rows": int(len(post)),
        "left_endpoint_missing_count": int((~rows_df["left_endpoint_sampled_flag"]).sum()),
        "right_endpoint_missing_count": int((~rows_df["right_endpoint_sampled_flag"]).sum()),
        "post_P0_left_endpoint_missing_count": int((~post["left_endpoint_sampled_flag"]).sum()),
        "post_P0_right_endpoint_missing_count": int((~post["right_endpoint_sampled_flag"]).sum()),
        "endpoint_complete_rows": int(rows_df["grid_endpoint_complete_flag"].sum()),
        "simple_geometric_h_match_count": int(rows_df["simple_geometric_h_match_flag"].sum()),
        "simple_geometric_h_mismatch_count": int((~rows_df["simple_geometric_h_match_flag"]).sum()),
        "post_P0_simple_geometric_h_match_count": int(post["simple_geometric_h_match_flag"].sum()),
        "post_P0_simple_geometric_h_mismatch_count": int((~post["simple_geometric_h_match_flag"]).sum()),
        "sample_count_min": int(rows_df["sample_count"].min()),
        "sample_count_max": int(rows_df["sample_count"].max()),
        "post_P0_sample_count_min": int(post["sample_count"].min()),
        "post_P0_sample_count_max": int(post["sample_count"].max()),
        "unique_offset_patterns": int(len(pattern_counter)),
        "unique_offset_patterns_post_P0": int(len(pattern_counter_post)),
        "pattern_coverage_top_1": float(sum(c for _, c in pattern_counter.most_common(1)) / total),
        "pattern_coverage_top_5": float(sum(c for _, c in pattern_counter.most_common(5)) / total),
        "pattern_coverage_top_10": float(sum(c for _, c in pattern_counter.most_common(10)) / total),
        "samples_on_lambda_event_fraction": samples_on_event_fraction,
        "samples_near_lambda_event_fraction": samples_near_fraction,
        "event_to_sample_alignment_score_min": float(rows_df["event_to_sample_alignment_score"].min()) if "event_to_sample_alignment_score" in rows_df else math.nan,
        "event_to_sample_alignment_score_mean": float(rows_df["event_to_sample_alignment_score"].mean()) if "event_to_sample_alignment_score" in rows_df else math.nan,
        "post_P0_event_to_sample_alignment_score_min": float(post["event_to_sample_alignment_score"].min()) if "event_to_sample_alignment_score" in post else math.nan,
        "post_P0_event_to_sample_alignment_score_mean": float(post["event_to_sample_alignment_score"].mean()) if "event_to_sample_alignment_score" in post else math.nan,
        "script_inspection_lambda_dependent_grid": False,
        "script_inspection_random_y_fill_possible": True,
        "script_inspection_h_grid_rule": "geometric_h_values(max_h): fixed small offsets plus rounded geomspace(1,max_h,36) plus max_h",
        "routeA_TJ_rule": "T_J={y} union {y+r: r is SR11 h-sample for (block_id,y), r<=h} union {y+h}",
        "proof_safe_TJ_rule_available": True,
        "recommended_TJ_definition": "routeA_sr11_available_subgrid_plus_endpoints",
        "csv_dependency_warning": "Do not define T_J by CSV rows; define the SR11 h-grid and Route-A subgrid rule.",
        "tj_extraction_failures": int((~rows_df["grid_endpoint_complete_flag"]).sum()),
        "pass_tj_grid_extraction_empirical": bool((~rows_df["grid_endpoint_complete_flag"]).sum() == 0),
    }

    by_rows: List[Dict[str, object]] = []
    for key in ["post_P0_flag", "simple_geometric_h_match_flag", "sample_count", "E_theta_sign", "threshold_relevant_flag", "forbidden_flag", "finite_zone_flag"]:
        by_rows.extend(aggregate(rows_df, key))

    failures = rows_df[~rows_df["grid_endpoint_complete_flag"]].copy()
    mismatch = rows_df[~rows_df["simple_geometric_h_match_flag"]].copy()

    paths = {
        "script": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_audit.py",
        "summary": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_summary.csv",
        "rows": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_rows.csv",
        "patterns": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_patterns.csv",
        "by_regime": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_by_regime.csv",
        "mismatches": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_geometric_h_mismatches.csv",
        "failures": OUT_DIR / "prime_mesh_r2q_hexc_tj_grid_extraction_failures.csv",
        "note": OUT_DIR / "Prime_Mesh_R2Q_HExc_TJ_Grid_Extraction_Audit_v1.md",
    }

    write_csv(paths["summary"], [summary])
    rows_df.to_csv(paths["rows"], index=False)
    write_csv(paths["patterns"], top_rows)
    write_csv(paths["by_regime"], by_rows)
    mismatch.to_csv(paths["mismatches"], index=False)
    failures.to_csv(paths["failures"], index=False)
    paths["note"].write_text(make_note(summary, paths), encoding="utf-8")
    update_manifest(paths.values())

    print("Wrote outputs:")
    for p in paths.values():
        print(p)
    print("Summary:")
    for k, v in summary.items():
        print(f"{k}={v}")


if __name__ == "__main__":
    main()
